name: C++ Build without Running

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Install SFML dependencies
      run: sudo apt-get install -y libsfml-dev

    - name: Compile hello world with SFML
      run: |
        mkdir -p build
        cd 01-01-hello-world
        g++ -o ../build/hello-world *.cpp -lsfml-graphics -lsfml-window -lsfml-system

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-artifact
        path: build
