name: C++ Build with SFML

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Install SFML dependencies
      run: sudo apt-get install -y libsfml-dev

    - name: Build and run hello world with SFML
      run: |
        mkdir build
        cd 01-01-hello-world
        g++ -o ../build/hello-world main.cpp -lsfml-graphics -lsfml-window -lsfml-system
        ../build/hello-world
