name: C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v1
      with:
        compiler: 'gcc' # or 'clang', depending on your preference

    - name: Build and run hello world
      run: |
        mkdir build
        cd 01-01-hello-world
        g++ -o ../build/hello-world main.cpp
        ../build/hello-world
